[package]
name = "ferreline"
version = "0.1.0-alpha.2"
edition = "2024"
license = "MIT"
description = "Rust library for interop with game Celeste"
readme = "README.md"
repository = "https://github.com/NewYearPrism/Ferreline.git"

[dependencies]
allocator-api2 = "0.2.21"
derive_more = { version = "2.0.1", default-features = false, features = [
    "error",
    "try_from",
    "deref",
] }
directed-visit = { version = "0.3.2", optional = true }
dotnet-io-binary = "0.1.0-alpha"
shared_vector = "0.4.4"

[dev-dependencies]
bumpalo = { version = "3.19.0", features = ["allocator-api2"] }
dotenvy = "0.15.7"
criterion = "0.7.0"
ferreline = { path = ".", features = ["visit"] }

[[bench]]
name = "my_benchmark"
harness = false

[features]
visit = ["dep:directed-visit"]
sync = []
